version: "3"

services:
  alpha:
    build: 
      dockerfile: ./Dockerfile
    image: "lvccwk/alpha:latest"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: "postgres:13"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alpha
      # POSTGRES_PORT: 5433
    ports:
      - "5433:5432"
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data